#!/usr/bin/env bash
# Source after activating Python; do not override the caller's environment.
export ACCV_ROOT="${ACCV_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
export ACCV_CACHE="${ACCV_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/accv}"
export PILOT_ROOT="${PILOT_ROOT:-$ACCV_ROOT/protocol}"
export PILOT_OUTPUT_ROOT="${PILOT_OUTPUT_ROOT:-$ACCV_ROOT/outputs}"
export REPOS_DIR="${REPOS_DIR:-$ACCV_CACHE/repos}"
export MODELS_DIR="${MODELS_DIR:-$ACCV_CACHE/models}"
export PBP_WORK="${PBP_WORK:-$PILOT_OUTPUT_ROOT/pbp}"
export GAIT_WORK="${GAIT_WORK:-$PILOT_OUTPUT_ROOT/gait}"
export YOLO_MODEL="${YOLO_MODEL:-$MODELS_DIR/ultralytics/yolov8x.pt}"
export EVAL_PROTOCOL_NAMES="${EVAL_PROTOCOL_NAMES:-crossview_cam2}"
export TORCH_HOME="${TORCH_HOME:-$MODELS_DIR/deepprivacy2/torch_home}"
export FVCORE_CACHE="${FVCORE_CACHE:-$MODELS_DIR/deepprivacy2/iopath_cache}"
export BASE_OUTPUT_DIR="${BASE_OUTPUT_DIR:-$PILOT_OUTPUT_ROOT/deepprivacy2_runtime}"
export WANDB_MODE="disabled"
export PYTHONUNBUFFERED="1"
export PYTHONNOUSERSITE="1"
export OMP_NUM_THREADS="${SLURM_CPUS_PER_TASK:-4}"
export MKL_NUM_THREADS="${SLURM_CPUS_PER_TASK:-4}"
